name: Unit Tests

on:
  push:
    branches:
      - task/unitTesting

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests
        run: |
          npm run test
