name: Node.js CI

on:
  push:
    branches: [task/unitTesting]

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      MONGO_URI: mongodb+srv://iq882:iq882@cluster0.hkm14qd.mongodb.net/linkify_testing?retryWrites=true&w=majority

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Navigate to App-src directory
      run: cd App-src

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
