name: Node.js CI

on:
  push:
    branches: [task/unitTesting]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Navigate to Linkify-src directory and run tests
      working-directory: ./Linkify-src
      run: |
        npm install
        npm run test -- --coverage --json

    - name: Check Test Coverage
      nyc report --reporter=text-summary --dir coverage > ./Linkify-src/coverage/coverage-summary.txt
      if [ -f ./Linkify-src/coverage/coverage-summary.txt ]; then
        COVERAGE=$(grep -oP '(?<=All files)\s+\K\d+%' ./Linkify-src/coverage/coverage-summary.txt)
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Test coverage below 80%: $COVERAGE"
          exit 1
        else
          echo "Test coverage above 80%: $COVERAGE"
        fi
      else
        echo "coverage-summary.txt file not found"
        exit 1
      fi





















    # - name: Run Tests
    #   run: npm run test
    #   env: 
    #     MONGO_URI: mongodb+srv://iq882:iq882@cluster0.hkm14qd.mongodb.net/linkify_testing?retryWrites=true&w=majority

# name: Node.js CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'

#     - name: Install dependencies and test
#       working-directory: ./Linkify-src
#       run: |
#         npm install
#         npm run test
